/**
 * Created by kras on 04.09.16.
 */
'use strict';
module.exports = {
  COLLECTION_LIST: 0,
  COLLECTION_LINK: 1,
  COLLECTION_LINKS: 2,
  COLLECTION_TABLE: 3,
  COLLECTION_HASHTAGS: 4,

  REF_STRING: 0,
  REF_LINK: 1,
  REF_INFO: 2,
  REF_HIERARCHY: 3,

  GEO_MAP: 0,
  GEO_LOCATOR: 1,
  GEO_CANVAS: 2
};
